apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress-tr
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: "sticky"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-service
          servicePort: hello-port
